config/routes.rb
Symenu::Application.routes.draw do
  resources :uploads

  resources :categories

  resources :menus
  resources :main

  root :to => 'main#index'

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  attr_accessible :menu, :category
  belongs_to :menu
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :information, :name, :photo, :menus
  has_many :categorizations
  has_many :menus, :through => :categorizations
  has_attached_file :photo, 
  			:styles => { :medium => "300x300>", :thumb => "100x100>" }
  			#:url => "/photos/:class/:attachment/:id/:style/:basename.:extension",
  			#:path => "/photos/:class/:attachment/:id/:style/:basename.:extension"
  validates :name, :information, :photo, :menus, :presence => true


  # validates :information, :name, :presence => true
  # Path = Application Directory
  # Url = Users will use to render
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :description, :name, :price, :category
  has_many :categorizations
  has_many :categories, :through => :categorizations

  validates :description, :name, :price, :category, :presence => true
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  attr_accessible :name, :logo
  has_attached_file :logo, 
  		:styles => {:medium => "300x300>", :max => "480x800>"}
  validates :name, :logo, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml # personalized XML
      # format.json { render json: @categories }
      #format.xml { render xml: @categories }

    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      # format.json { render json: @category }
      format.xml { render xml: @categories }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        # format.json { render json: @menu, status: :created, location: @menu }
      else
        format.html { render action: "new" }
        #format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end


  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
    end

  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  # GET /menus
  # GET /menus.json
  def index
    #@menus = Menu.all
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      # format.json { render json: @menus }
      format.xml { render xml: @categories }


    end
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
    #@menu = Menu.find(params[:id])
    @categories = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      # format.json { render json: @menu } 
      format.xml{ render xml: @categories }

    end
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
    
    respond_to do |format|
      format.html # index.html.erb
      # format.json { render json: @menus }
      format.xml { render xml: @menus }


    end
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
    @menu = Menu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      # format.json { render json: @menu } 
      format.xml{ render xml: @menus }

    end
  end

  # GET /menus/new
  # GET /menus/new.json
  def new
    @menu = Menu.new
    @categories = Category.all
  end

  # GET /menus/1/edit
  def edit
    @menu = Menu.find(params[:id])
    @categories = Category.all
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(params[:menu])

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        # format.json { render json: @menu, status: :created, location: @menu }
      else
        format.html { render action: "new" }
        #format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end

  end

  # PUT /menus/1
  # PUT /menus/1.json
  def update
    @menu = Menu.find(params[:id])
  end


  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url }
    end

  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml
    end
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
    @upload = Upload.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      # format.xml { render xml: @upload }
    end
  end

  # GET /uploads/new
  # GET /uploads/new.json
  def new
    @upload = Upload.new

  end

  # GET /uploads/1/edit
  def edit
    @upload = Upload.find(params[:id])
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.new(params[:upload])

    respond_to do |format|
      if @upload.save
        format.html { redirect_to @upload, notice: 'Upload was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /uploads/1
  # PUT /uploads/1.json
  def update
    @upload = Upload.find(params[:id])

    respond_to do |format|
      if @upload.update_attributes(params[:upload])
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload = Upload.find(params[:id])
    @upload.destroy

    respond_to do |format|
      format.html { redirect_to uploads_url }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
	# Use with the same arguments as image_tag. Returns the same, except including
# a full path in the src URL. Useful for templates that will be rendered into
# emails etc.
def absolute_image_tag(*args)
  raw(image_tag(*args).sub /src="(.*?)"/, "src=\"#{request.protocol}#{request.host_with_port}" + '\1"')
end
def absolute_image_path(*args)
  raw(image_path(*args).sub /src="(.*?)"/, "src=\"#{request.protocol}#{request.host_with_port}" + '\1"')
end

def image_url(source)
	"#{root_url}#{image_path(source)}"	
end

end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category, :url => categories_path, :html => { :multipart => true }) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :information %><br />
    <%= f.text_area :information, :rows => 6 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Photo</th>
    <th>Name</th>
    <th>Information</th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= image_tag image_url(category.photo.url(:thumb)) %></td>
    <td><%= category.name %></td>
    <td><%= category.information %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<p>
	<b>Photo:</b>
	<%= image_tag @category.photo.url %>
</p>
<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Information:</b>
  <%= @category.information %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_nav.html.erb
<nav class="top-bar">
  <ul>
    <li class="name"><h1><a href="#">Show Your Menu</a></h1></li>
    <li class="toggle-topbar"><a href="#"></a></li>
  </ul>
  <section>
    <ul class="left">
      <li><a href="#">Features</a></li>
      <li><a href="#">Showcase</a></li>
      <li><a href="#">Pricing</a></li>
      <li><a href="#">Sign Up</a></li>
    </ul>

    <ul class="right">
      <li><a href="#">contact</a></li>
      <li><a href="#">about</a></li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
	<title><%= content_for?(:title) ? yield(:title) : "Show Your Menu" %></title>
  
	<!-- Included CSS Files -->
	<%= stylesheet_link_tag    "application" %>
	
	<!-- Included JS Files  -->
	<%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="top-bar">
		<ul>
			<li class="name"><h1><a href="#">Show Your Menu</a></h1></li>
    		<li class="toggle-topbar"><a href="#"></a></li>
    	</ul>
		<section>
		    <ul class="left">
		      <li><a href="#">Features</a></li>
		      <li><a href="#">Showcase</a></li>
		      <li><a href="#">Pricing</a></li>
		      <li><a href="#">Sign Up</a></li>
		    </ul>

		    <ul class="right">
		      <li><a href="#">contact</a></li>
		      <li><a href="#">about</a></li>
		    </ul>
		  </section>
		</nav>

		<div class="row">
			<div class="three columns">
				<ul class="nav-bar vertical">
					<li><%= link_to 'add logo', uploads_path %> </li>
					<li><%= link_to 'add Category', categories_path %></li>
					<li><%= link_to 'add Menu', menus_path %></li>

				</ul>
			</div>
			<div class="nine columns">
			
				<%= yield %>
			</div>
		</div>

		



  
</body>
</html>

app/views/main/index.html.erb
<h1>Listing menus</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Menu Id</th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= image_tag (category.photo.url(:thumb)) %></td>
    <td><%= category.name %></td>
    <td><%= category.information %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %>
    <%= collection_select(:menu, :name, Category.all, :id, :name) %>
    
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 6 %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<h1>Listing menus</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Menu Id</th>
  </tr>

<% @menus.each do |menu| %>
  <tr>
    <td><%= menu.name %></td>
    <td><%= menu.name %></td>
    <td><%= menu.description %></td>
    <td><%= menu.id %></td>
    <td><%= link_to 'Show', menu %></td>
    <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
    <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @menu.name %>
</p>

<p>
  <b>Description:</b>
  <%= @menu.description %>
</p>

<p>
  <b>Price:</b>
  <%= @menu.price %>
</p>
<p>
	<b>Menu ID??</b>
</p>


<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>

app/views/uploads/_form.html.erb
<%= form_for(@upload, :url => uploads_path, :html => { :multipart => true})  do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :logo %>
    <%= f.file_field :logo %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<h1>Listing uploads</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Image</th>
    <th></th>
    <th></th>
  </tr>

<% @uploads.each do |upload| %>
  <tr>
    <td><%= upload.name %></td>
    <td><%= image_tag image_url(upload.logo.url(:max)) %></td>
    <td><%= link_to 'Show', upload %></td>
    <td><%= link_to 'Edit', edit_upload_path(upload) %></td>
    <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Upload', new_upload_path %>

app/views/uploads/new.html.erb
<h1>New upload</h1>

<%= render 'form' %>

<%= link_to 'Back', uploads_path %>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>
<p>
<%= image_tag @upload.logo.url(:max) %>
</p>
<p>
  <b>Name:</b>
  <%= @upload.name %>
</p>


<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>